//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiProductsWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_id { get; set; }
        public Nullable<int> Product_id { get; set; }
        public Nullable<int> Person_id { get; set; }
        public Nullable<int> Order_quantity { get; set; }
        public Nullable<int> Order_num { get; set; }
    
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
    }
}
